---
version: 2.1

workflows:
  circleci-orbs-pipeline:
    jobs:
      - dev-release:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - publish:
          requires:
            - dev-release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

executors:

  circleci-orb-agent:
    docker:
      - image: quay.io/feedyard/circleci-orb-agent
    environment:
      TAG_MSG_ORB_IDENTIFIER: orb
      TAG_MSG_SEMVER_IDENTIFIER: level
      BASH_ENV: local.env


jobs:

  dev-release:
    executor: circleci-orb-agent
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: decrypt secrets
          command: openssl aes-256-cbc -d -in env.ci -out local.env -k $FEEDYARD_CIRCLECI_ENC
      - run:
          name: lint
          command: yamllint .
      - run:
          name: validate orbs
          command: ash scripts/validate_orbs.sh
      - run:
          name: SHA1/volatile development release
          command: |
            for ORB in src/*; do
              orbname=$(basename $ORB)
              # dev release using SHA1 as release version
              circleci orb publish ${ORB}/orb.yaml $CIRCLE_PROJECT_USERNAME/$orbname@dev:$CIRCLE_SHA1 --token $CIRCLECI_API_TOKEN
              # dev release using 'volatile' as release version
              circleci orb publish ${ORB}/orb.yaml $CIRCLE_PROJECT_USERNAME/$orbname@dev:volatile --token $CIRCLECI_API_TOKEN
            done

  publish:
    executor: circleci-orb-agent
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: decrypt secrets
          command: openssl aes-256-cbc -d -in env.ci -out local.env -k $FEEDYARD_CIRCLECI_ENC
      - run:
          name: publish incremental orb version
          command: |
            orbname=$(git show $CIRCLE_TAG | awk '{for(i=1;i<=NF;i++)if($i~/$TAG_MSG_ORB_IDENTIFIER/)print $(i+1)}')
            semver=$(git show $CIRCLE_TAG | awk '{for(i=1;i<=NF;i++)if($i~/$TAG_MSG_SEMVER_IDENTIFIER/)print $(i+1)}')
            circleci orb publish promote $CIRCLE_PROJECT_USERNAME/$orbname@dev:$CIRCLE_SHA1 $semver --token $CIRCLECI_API_TOKEN
