---
version: 2.1

workflows:
  circleci-orbs-pipeline:
    jobs:
      - dev-release
      - approve-publish:
          type: approval
          requires:
            - dev-release
      - publish:
          requires:
            - approve-publish

executors:

  circleci-orb-agent:
    docker:
      - image: quay.io/feedyard/circleci-orb-agent
    environment:
      BASH_ENV: local.env


jobs:

  dev-release:
    executor: circleci-orb-agent
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: decrypt secrets
          command: openssl aes-256-cbc -d -in env.ci -out local.env -k $FEEDYARD_CIRCLECI_ENC
      - run:
          name: validate yaml
          command: yamllint .
      - run:
          name: validate orbs
          command: ash scripts/validate_orbs.sh
      - run:
          name: SHA1/latest development release
          command: |
            LAST_SUCCESSFUL_COMMIT=$(curl -Ss -u "$CIRCLECI_API_TOKEN:" "https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?filter=completed&limit=1" | jq -r '.[0]["vcs_revision"]')
            echo 'last=$LAST_SUCCESSFUL_COMMIT'
            for ORB in src/*; do
              if [[ $(git diff $LAST_SUCCESSFUL_COMMIT:${ORB}/orb.yaml ${ORB}/orb.yaml) ]]; then
                orbname=$(basename $ORB)
                # dev release using SHA1 as release version
                circleci orb publish ${ORB}/orb.yaml $CIRCLE_PROJECT_USERNAME/$orbname@dev:$CIRCLE_SHA1 --token $CIRCLECI_API_TOKEN
                # dev release using 'latest' as release version
                circleci orb publish ${ORB}/orb.yaml $CIRCLE_PROJECT_USERNAME/$orbname@dev:latest --token $CIRCLECI_API_TOKEN
              fi
            done

  publish:
    executor: circleci-orb-agent
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: decrypt secrets
          command: openssl aes-256-cbc -d -in env.ci -out local.env -k $FEEDYARD_CIRCLECI_ENC
      - run:
          name: publish incremental orb version
          command: |
            LAST_SUCCESSFUL_COMMIT=$(curl -Ss -u "$CIRCLECI_API_TOKEN:" "https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?filter=completed&limit=1" | jq -r '.[0]["vcs_revision"]')
            for ORB in src/*; do
              if [[ $(git diff $LAST_SUCCESSFUL_COMMIT:${ORB}/orb.yaml) ]]; then
                orbname=$(basename $ORB)
                semver='patch'
                if [[ -e ${ORB}/minor ]]; then
                  semver='minor'
                fi
                if [[ -e ${ORB}/major ''; then
                  semver='major'
                fi
                # dev release using 'latest' as release version
                circleci orb publish promote $CIRCLE_PROJECT_USERNAME/$orbname@dev:latest $semver --token $CIRCLECI_API_TOKEN
              fi
            done
