---
version: 2.1

workflows:
  circleci-orbs-pipeline:
    jobs:
      - dev-release
      - approve-publish:
          type: approval
          requires:
            - dev-release
      - publish:
          requires:
            - approve-publish

executors:

  circleci-orb-agent:
    docker:
      - image: quay.io/feedyard/circleci-orb-agent
    environment:
      BASH_ENV: local.env


jobs:

  dev-release:
    executor: circleci-orb-agent
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: decrypt secrets
          command: openssl aes-256-cbc -d -in env.ci -out local.env -k $FEEDYARD_CIRCLECI_ENC
      - run:
          name: validate yaml
          command: yamllint .
      - run:
          name: validate orbs
          command: ash scripts/validate_orbs.sh
      - run:
          name: SHA1/latest development release
          command: |
            for ORB in src/*; do
              orbname=$(basename $ORB)
              circleci orb source $CIRCLE_PROJECT_USERNAME/$orbname@dev:latest > $orbname.latest
              if [[ $(diff <(printf %s "$(< ${ORB}/orb.yaml)") <(printf %s "$(< $orbname.latest)")) ]]; then
                echo "dev-release of $CIRCLE_PROJECT_USERNAME/$orbname"
                circleci orb publish $CIRCLE_PROJECT_USERNAME/$orbname@dev:$CIRCLE_SHA1 --token $CIRCLECI_API_TOKEN
                circleci orb publish $CIRCLE_PROJECT_USERNAME/$orbname@dev:latest --token $CIRCLECI_API_TOKEN
              fi
            done

  publish:
    executor: circleci-orb-agent
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: decrypt secrets
          command: openssl aes-256-cbc -d -in env.ci -out local.env -k $FEEDYARD_CIRCLECI_ENC
      - run:
          name: publish incremental orb version
          command: |
            for ORB in src/*; do
              orbname=$(basename $ORB)
              circleci orb source $CIRCLE_PROJECT_USERNAME/$orbname@volatile > $orbname.volatile
              if [[ $(diff <(printf %s "$(< ${ORB}/orb.yaml)") <(printf %s "$(< $orbname.volatile)")) ]]; then
                echo "publish $CIRCLE_PROJECT_USERNAME/$orbname"
                circleci orb publish promote $CIRCLE_PROJECT_USERNAME/$orbname@dev:latest patch --token $CIRCLECI_API_TOKEN
              fi
            done
